# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/classifier.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/classifier.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto/classifier.proto\x12\nclassifier\"4\n\x0f\x43lassifyRequest\x12\x10\n\x08\x66\x65\x61tures\x18\x01 \x03(\x02\x12\x0f\n\x07\x66low_id\x18\x02 \x01(\t\"8\n\x10\x43lassifyResponse\x12\x13\n\x0bprobability\x18\x01 \x01(\x02\x12\x0f\n\x07verdict\x18\x02 \x01(\t2Z\n\x11\x43lassifierService\x12\x45\n\x08\x43lassify\x12\x1b.classifier.ClassifyRequest\x1a\x1c.classifier.ClassifyResponseB\x13Z\x11proto/classifier/b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.classifier_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\021proto/classifier/'
  _globals['_CLASSIFYREQUEST']._serialized_start=38
  _globals['_CLASSIFYREQUEST']._serialized_end=90
  _globals['_CLASSIFYRESPONSE']._serialized_start=92
  _globals['_CLASSIFYRESPONSE']._serialized_end=148
  _globals['_CLASSIFIERSERVICE']._serialized_start=150
  _globals['_CLASSIFIERSERVICE']._serialized_end=240
# @@protoc_insertion_point(module_scope)
