// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: proto/classifier/classifier.proto

package classifier

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос к ML модели — вектор признаков одного flow
type ClassifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Features      []float32              `protobuf:"fixed32,1,rep,packed,name=features,proto3" json:"features,omitempty"`  // float64[10]
	FlowId        string                 `protobuf:"bytes,2,opt,name=flow_id,json=flowId,proto3" json:"flow_id,omitempty"` // src_ip:src_port->dst_ip:dst_port
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyRequest) Reset() {
	*x = ClassifyRequest{}
	mi := &file_proto_classifier_classifier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyRequest) ProtoMessage() {}

func (x *ClassifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_classifier_classifier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyRequest.ProtoReflect.Descriptor instead.
func (*ClassifyRequest) Descriptor() ([]byte, []int) {
	return file_proto_classifier_classifier_proto_rawDescGZIP(), []int{0}
}

func (x *ClassifyRequest) GetFeatures() []float32 {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *ClassifyRequest) GetFlowId() string {
	if x != nil {
		return x.FlowId
	}
	return ""
}

// Ответ от ML модели
type ClassifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Probability   float32                `protobuf:"fixed32,1,opt,name=probability,proto3" json:"probability,omitempty"` // вероятность атаки 0.0 - 1.0
	Verdict       string                 `protobuf:"bytes,2,opt,name=verdict,proto3" json:"verdict,omitempty"`           // "benign", "suspicious", "attack"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassifyResponse) Reset() {
	*x = ClassifyResponse{}
	mi := &file_proto_classifier_classifier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassifyResponse) ProtoMessage() {}

func (x *ClassifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_classifier_classifier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassifyResponse.ProtoReflect.Descriptor instead.
func (*ClassifyResponse) Descriptor() ([]byte, []int) {
	return file_proto_classifier_classifier_proto_rawDescGZIP(), []int{1}
}

func (x *ClassifyResponse) GetProbability() float32 {
	if x != nil {
		return x.Probability
	}
	return 0
}

func (x *ClassifyResponse) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

var File_proto_classifier_classifier_proto protoreflect.FileDescriptor

const file_proto_classifier_classifier_proto_rawDesc = "" +
	"\n" +
	"!proto/classifier/classifier.proto\x12\n" +
	"classifier\"F\n" +
	"\x0fClassifyRequest\x12\x1a\n" +
	"\bfeatures\x18\x01 \x03(\x02R\bfeatures\x12\x17\n" +
	"\aflow_id\x18\x02 \x01(\tR\x06flowId\"N\n" +
	"\x10ClassifyResponse\x12 \n" +
	"\vprobability\x18\x01 \x01(\x02R\vprobability\x12\x18\n" +
	"\averdict\x18\x02 \x01(\tR\averdict2Z\n" +
	"\x11ClassifierService\x12E\n" +
	"\bClassify\x12\x1b.classifier.ClassifyRequest\x1a\x1c.classifier.ClassifyResponseB\x13Z\x11proto/classifier/b\x06proto3"

var (
	file_proto_classifier_classifier_proto_rawDescOnce sync.Once
	file_proto_classifier_classifier_proto_rawDescData []byte
)

func file_proto_classifier_classifier_proto_rawDescGZIP() []byte {
	file_proto_classifier_classifier_proto_rawDescOnce.Do(func() {
		file_proto_classifier_classifier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_classifier_classifier_proto_rawDesc), len(file_proto_classifier_classifier_proto_rawDesc)))
	})
	return file_proto_classifier_classifier_proto_rawDescData
}

var file_proto_classifier_classifier_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_classifier_classifier_proto_goTypes = []any{
	(*ClassifyRequest)(nil),  // 0: classifier.ClassifyRequest
	(*ClassifyResponse)(nil), // 1: classifier.ClassifyResponse
}
var file_proto_classifier_classifier_proto_depIdxs = []int32{
	0, // 0: classifier.ClassifierService.Classify:input_type -> classifier.ClassifyRequest
	1, // 1: classifier.ClassifierService.Classify:output_type -> classifier.ClassifyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_classifier_classifier_proto_init() }
func file_proto_classifier_classifier_proto_init() {
	if File_proto_classifier_classifier_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_classifier_classifier_proto_rawDesc), len(file_proto_classifier_classifier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_classifier_classifier_proto_goTypes,
		DependencyIndexes: file_proto_classifier_classifier_proto_depIdxs,
		MessageInfos:      file_proto_classifier_classifier_proto_msgTypes,
	}.Build()
	File_proto_classifier_classifier_proto = out.File
	file_proto_classifier_classifier_proto_goTypes = nil
	file_proto_classifier_classifier_proto_depIdxs = nil
}
